%%{init: {'flowchart': {'curve': 'stepChild'}}}%%
graph LR
    classDef redPin fill:#f00, stroke:#f00, width:8px, height:8px, color:#000, font-weight:bold;
    classDef bluePin fill:#00f, stroke:#00f, width:8px, height:8px, color:#000, font-weight:bold;
    
    classDef box fill:#fff,stroke:#000,stroke-width:2px;

subgraph power_unit [power_unit]
		power_unitplus(( plus ))
		power_unitminus(( minus ))
	end

subgraph front_right [front_right]
		front_rightarduino_v(( arduino_v ))
		front_rightground(( ground ))
		front_rightm_minus(( m_minus ))
		front_rightm_plus(( m_plus ))
		front_rightpin_a(( pin_a ))
		front_rightpin_b(( pin_b ))
	end

subgraph front_left [front_left]
		front_leftarduino_v(( arduino_v ))
		front_leftground(( ground ))
		front_leftm_minus(( m_minus ))
		front_leftm_plus(( m_plus ))
		front_leftpin_a(( pin_a ))
		front_leftpin_b(( pin_b ))
	end

subgraph back_right [back_right]
		back_rightarduino_v(( arduino_v ))
		back_rightground(( ground ))
		back_rightm_minus(( m_minus ))
		back_rightm_plus(( m_plus ))
		back_rightpin_a(( pin_a ))
		back_rightpin_b(( pin_b ))
	end

subgraph back_left [back_left]
		back_leftarduino_v(( arduino_v ))
		back_leftground(( ground ))
		back_leftm_minus(( m_minus ))
		back_leftm_plus(( m_plus ))
		back_leftpin_a(( pin_a ))
		back_leftpin_b(( pin_b ))
	end

subgraph flash_A [flash_A]
		flash_Aarduino_v_in(( arduino_v_in ))
		flash_Aground_in(( ground_in ))
		flash_Ascl(( scl ))
		flash_Asda(( sda ))
		flash_Aarduino_v_out(( arduino_v_out )) --- front_rightarduino_v(( front_rightarduino_v ))
		flash_Aground_out(( ground_out )) --- front_rightground(( front_rightground ))
		flash_Aplus_12v(( plus_12v )) --- front_rightm_plus(( front_rightm_plus ))
		flash_Aminus_12v(( minus_12v )) --- front_rightm_minus(( front_rightm_minus ))
		flash_Apin_a(( pin_a )) --- front_rightpin_a(( front_rightpin_a ))
		flash_Apin_b(( pin_b )) --- front_rightpin_b(( front_rightpin_b ))
	end

subgraph flash_A [flash_A]
		flash_Aarduino_v_in(( arduino_v_in ))
		flash_Aground_in(( ground_in ))
		flash_Ascl(( scl ))
		flash_Asda(( sda ))
		flash_Aarduino_v_out(( arduino_v_out )) --- front_leftarduino_v(( front_leftarduino_v ))
		flash_Aground_out(( ground_out )) --- front_leftground(( front_leftground ))
		flash_Aplus_12v(( plus_12v )) --- front_leftm_plus(( front_leftm_plus ))
		flash_Aminus_12v(( minus_12v )) --- front_leftm_minus(( front_leftm_minus ))
		flash_Apin_a(( pin_a )) --- front_leftpin_a(( front_leftpin_a ))
		flash_Apin_b(( pin_b )) --- front_leftpin_b(( front_leftpin_b ))
	end

subgraph flash_A [flash_A]
		flash_Aarduino_v_in(( arduino_v_in ))
		flash_Aground_in(( ground_in ))
		flash_Ascl(( scl ))
		flash_Asda(( sda ))
		flash_Aarduino_v_out(( arduino_v_out )) --- back_rightarduino_v(( back_rightarduino_v ))
		flash_Aground_out(( ground_out )) --- back_rightground(( back_rightground ))
		flash_Aplus_12v(( plus_12v )) --- back_rightm_plus(( back_rightm_plus ))
		flash_Aminus_12v(( minus_12v )) --- back_rightm_minus(( back_rightm_minus ))
		flash_Apin_a(( pin_a )) --- back_rightpin_a(( back_rightpin_a ))
		flash_Apin_b(( pin_b )) --- back_rightpin_b(( back_rightpin_b ))
	end

subgraph flash_A [flash_A]
		flash_Aarduino_v_in(( arduino_v_in ))
		flash_Aground_in(( ground_in ))
		flash_Ascl(( scl ))
		flash_Asda(( sda ))
		flash_Aarduino_v_out(( arduino_v_out )) --- back_leftarduino_v(( back_leftarduino_v ))
		flash_Aground_out(( ground_out )) --- back_leftground(( back_leftground ))
		flash_Aplus_12v(( plus_12v )) --- back_leftm_plus(( back_leftm_plus ))
		flash_Aminus_12v(( minus_12v )) --- back_leftm_minus(( back_leftm_minus ))
		flash_Apin_a(( pin_a )) --- back_leftpin_a(( back_leftpin_a ))
		flash_Apin_b(( pin_b )) --- back_leftpin_b(( back_leftpin_b ))
	end

subgraph i2c_bus [i2c_bus]
		i2c_busarduino_v_in(( arduino_v_in ))
		i2c_busground_in(( ground_in ))
		i2c_busscl_in(( scl_in ))
		i2c_bussda_in(( sda_in ))
		i2c_busv_out_1(( v_out_1 )) --- flash_ANone(( flash_ANone ))
		i2c_busg_out_1(( g_out_1 )) --- flash_ANone(( flash_ANone ))
		i2c_busscl_out_1(( scl_out_1 )) --- flash_ANone(( flash_ANone ))
		i2c_bussda_out_1(( sda_out_1 )) --- flash_ANone(( flash_ANone ))
		i2c_busv_out_2(( v_out_2 )) --- flash_ANone(( flash_ANone ))
		i2c_busg_out_2(( g_out_2 )) --- flash_ANone(( flash_ANone ))
		i2c_busscl_out_2(( scl_out_2 )) --- flash_ANone(( flash_ANone ))
		i2c_bussda_out_2(( sda_out_2 )) --- flash_ANone(( flash_ANone ))
		i2c_busv_out_3(( v_out_3 )) --- flash_ANone(( flash_ANone ))
		i2c_busg_out_3(( g_out_3 )) --- flash_ANone(( flash_ANone ))
		i2c_busscl_out_3(( scl_out_3 )) --- flash_ANone(( flash_ANone ))
		i2c_bussda_out_3(( sda_out_3 )) --- flash_ANone(( flash_ANone ))
		i2c_busv_out_4(( v_out_4 )) --- flash_ANone(( flash_ANone ))
		i2c_busg_out_4(( g_out_4 )) --- flash_ANone(( flash_ANone ))
		i2c_busscl_out_4(( scl_out_4 )) --- flash_ANone(( flash_ANone ))
		i2c_bussda_out_4(( sda_out_4 )) --- flash_ANone(( flash_ANone ))
	end

subgraph arduino_nano [arduino_nano]
		arduino_nanoarduino_v(( arduino_v )) --- i2c_busNone(( i2c_busNone ))
		arduino_nanoground(( ground )) --- i2c_busNone(( i2c_busNone ))
		arduino_nanoA5(( A5 )) --- i2c_busNone(( i2c_busNone ))
		arduino_nanoA4(( A4 )) --- i2c_busNone(( i2c_busNone ))
	end











    subgraph Voltage [Voltage Source]
        p_out(( +V )):::redPin
        m_out(( -V )):::bluePin
    end

    subgraph Conventer [DC-DC Converter]
        direction LR
        conv_p_in(( )):::redPin ~~~ conv_p_out(( )):::redPin
        conv_m_in(( )):::bluePin ~~~ conv_m_out(( )):::bluePin
    end

    subgraph CarMotor [Car Motor]
        mot_p_in(( )):::redPin
        mot_m_in(( )):::bluePin
    end

    
    p_out --- conv_p_in
    m_out --- conv_m_in
    conv_p_out --- mot_p_in
    conv_m_out --- mot_m_in

    
    linkStyle 2 stroke:#f00,stroke-width:2px;
    linkStyle 3 stroke:#00f,stroke-width:2px;
    
    linkStyle 0 stroke:#f00,stroke-width:2px;
    linkStyle 1 stroke:#00f,stroke-width:2px;

    
    style Voltage fill:#f9f9f9,stroke:#333,stroke-width:2px
    style Conventer fill:#fff,stroke:#000,stroke-width:2px
    style CarMotor fill:#fff,stroke:#000,stroke-width:2px
